require("config.lazy")
require('config.core.options')
require('config.core.remap')
require('config.core.macros')

require('config.after.telescope')
require('config.after.treesitter')
require('config.after.comment')
require('config.after.gitsigns')
require('config.after.nvim_cmp')
require('config.after.mason')
require('config.after.lspconfig')
require('config.after.oil')
require('config.after.indent-blankline')
require('config.after.theme')
require('config.after.nvim-surround')
